import type { StateCreator } from "zustand";
import type { CourseSlice } from "../types/course";

export const createCourseSlice: StateCreator<CourseSlice> = (set, get) => ({
  loading: false,
  sort: "latest",
  pagination: {
    page: 1,
    setPage: (page) => {
      const { pagination } = get();
      set({ pagination: { ...pagination, page } });
    },
    pages: 10,
    limit: 10,
    total: 100,
  },
  setSort: (sort) => {
    set({ sort });
  },
  search: "",
  setSearch: (search) => set({ search }),
  filters: {
    price: [0, -1],
    categories: [],
    duration: new Set(),
    rating: 0,
    lessons: [0, -1],
  },
  setFilters: (filters: CourseSlice["filters"]) => {
    set({ filters });
  },
  course: {
    id: 6,
    name: "JavaScript Mastery",
    tagline: "Master JavaScript like a professional",
    description:
      "This course is designed for developers who want to master React and Next.js by building real-world, full-stack AI-powered applications. Instead of learning concepts in isolation, you’ll build production-grade projects using modern tools like Convex, Supabase, Drizzle ORM, and secure payment gateways. Each module takes you from fundamentals to deployment, ensuring you understand both how things work and why they work that way. You’ll start by strengthening your React and Next.js foundations - routing, components, server actions, caching, and performance optimization. Then you’ll move into backend development using Convex and Supabase to create scalable databases, authentication systems, and API layers. You’ll learn relational modeling with Drizzle ORM, manage global state with  Zustand, or Context, and implement real payment flows using industry-standard gateways. The course includes multiple AI-based projects where you integrate models from OpenAI, Gemini, and other providers to create intelligent SaaS applications. You’ll build dashboards, file-handling systems, chat assistants, automation tools, and more. Finally, you’ll deploy your applications using modern hosting platforms and learn how to optimize them for real users. This is a complete, hands-on course that gives you the skills needed to build and ship full-stack, AI-driven web apps confidently. This course is a one stop solution to master React and NextJS so that you can ship your next project with confidence!",
    owner: 11,
    level: "intermediate",
    is_banned: false,
    status: "published",
    students_enrolled: 10000,
    ban_reason: null,
    skills: ["javascript", "typescript", "react.js", "tailwind"],
    cover:
      "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780987669/lms/course/yndzt0xxjwmgkyrucwqy.jpg",
    category: "programming",
    price: 2199,
    rating_sum: 45,
    rating_count: 10,
    duration: 7200,
    owner_name: "Shadcn",
    owner_avatar: "/avatar-small.png",
    lessons: 5,
    created_at: "2026-06-09T06:05:01.891Z",
  },
  setCourse: (courseId: number) => {
    const { courses } = get();
    const course = courses.find((item) => item.id === courseId);
    if (!course) return null;
    set({
      course: {
        ...course,
        description: "",
        owner_name: "Shivam",
        owner_avatar: "/avatar-small.png",
      },
    });
    return {
      ...course,
      description: "",
      owner_name: "Shivam",
      owner_avatar: "/avatar-small.png",
    };
  },
  enrolledCourses: [
    {
      id: 6,
    },
  ],
  progress: { completed: 1, total: 2 },
  courses: [
    {
      id: 6,
      name: "JavaScript Mastery",
      tagline: "Master JavaScript like a professional",
      owner: 11,
      level: "intermediate",
      is_banned: false,
      status: "published",
      students_enrolled: 1,
      ban_reason: null,
      skills: ["javascript"],
      cover:
        "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780987669/lms/course/yndzt0xxjwmgkyrucwqy.jpg",
      category: "programming",
      price: 2199,
      rating_sum: 4,
      rating_count: 1,
      duration: 7200,
      lessons: 5,
      created_at: "2026-06-09T06:05:01.891Z",
    },
    {
      id: 3,
      name: "Styling using CSS",
      tagline:
        "Cascading Style Sheets are an important part of webpage to design and align the webpage",
      owner: 11,
      level: "beginner",
      is_banned: false,
      status: "published",
      students_enrolled: 1,
      ban_reason: null,
      skills: ["CSS"],
      cover:
        "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780988065/lms/course/fegjy1rmynrizittty3p.jpg",
      category: "styling",
      price: 299,
      rating_sum: 10,
      rating_count: 3,
      duration: 3600,
      lessons: 2,
      created_at: "2026-05-31T07:32:04.258Z",
    },
    {
      id: 2,
      name: "React Tutorial",
      tagline: "Learn React component based Library managed by Meta",
      owner: 11,
      level: "beginner",
      is_banned: false,
      status: "published",
      students_enrolled: 0,
      ban_reason: null,
      skills: ["react", "HTML", "CSS", "JavaScript"],
      cover:
        "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780988197/lms/course/hcghp49jrk9favwtukme.jpg",
      category: "programming",
      price: 0,
      rating_sum: 12,
      rating_count: 3,
      duration: 270,
      lessons: 3,
      created_at: "2026-05-31T07:31:28.660Z",
    },
  ],
  suggestedCourses: [
    {
      id: 6,
      name: "JavaScript Mastery",
      tagline: "Master JavaScript like a professional",
      owner: 11,
      level: "intermediate",
      is_banned: false,
      status: "published",
      students_enrolled: 1,
      ban_reason: null,
      skills: ["javascript"],
      cover:
        "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780987669/lms/course/yndzt0xxjwmgkyrucwqy.jpg",
      category: "programming",
      price: 1,
      rating_sum: 1284,
      rating_count: 300,
      duration: 0,
      lessons: 0,
      created_at: "2026-06-09T06:05:01.891Z",
    },
    {
      id: 2,
      name: "React Tutorial",
      tagline: "Learn React component based Library managed by Meta",
      owner: 11,
      level: "beginner",
      is_banned: false,
      status: "published",
      students_enrolled: 0,
      ban_reason: null,
      skills: null,
      cover:
        "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780988197/lms/course/hcghp49jrk9favwtukme.jpg",
      category: "programming",
      price: 2199,
      rating_sum: 12,
      rating_count: 3,
      duration: 270,
      lessons: 3,
      created_at: "2026-05-31T07:31:28.660Z",
    },
    {
      id: 3,
      name: "Styling using CSS",
      tagline:
        "Cascading Style Sheets are an important part of webpage to design and align the webpage",
      owner: 11,
      level: "beginner",
      is_banned: false,
      status: "published",
      students_enrolled: 1,
      ban_reason: null,
      skills: null,
      cover:
        "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780988065/lms/course/fegjy1rmynrizittty3p.jpg",
      category: "programming",
      price: 299,
      rating_sum: 0,
      rating_count: 0,
      duration: 0,
      lessons: 0,
      created_at: "2026-05-31T07:32:04.258Z",
    },
  ],
  recentCourses: [
    {
      id: 6,
      name: "JavaScript Mastery",
      tagline: "Master JavaScript like a professional",
      owner: 11,
      level: "intermediate",
      is_banned: false,
      status: "published",
      students_enrolled: 1,
      ban_reason: null,
      skills: ["javascript"],
      cover:
        "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780987669/lms/course/yndzt0xxjwmgkyrucwqy.jpg",
      category: "programming",
      price: 1,
      rating_sum: 1284,
      rating_count: 300,
      duration: 0,
      lessons: 0,
      created_at: "2026-06-09T06:05:01.891Z",
    },
    {
      id: 2,
      name: "React Tutorial",
      tagline: "Learn React component based Library managed by Meta",
      owner: 11,
      level: "beginner",
      is_banned: false,
      status: "published",
      students_enrolled: 0,
      ban_reason: null,
      skills: null,
      cover:
        "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780988197/lms/course/hcghp49jrk9favwtukme.jpg",
      category: "programming",
      price: 2199,
      rating_sum: 12,
      rating_count: 3,
      duration: 270,
      lessons: 3,
      created_at: "2026-05-31T07:31:28.660Z",
    },
    {
      id: 3,
      name: "Styling using CSS",
      tagline:
        "Cascading Style Sheets are an important part of webpage to design and align the webpage",
      owner: 11,
      level: "beginner",
      is_banned: false,
      status: "published",
      students_enrolled: 1,
      ban_reason: null,
      skills: null,
      cover:
        "https://res.cloudinary.com/dv3qbj0bn/image/upload/v1780988065/lms/course/fegjy1rmynrizittty3p.jpg",
      category: "programming",
      price: 299,
      rating_sum: 0,
      rating_count: 0,
      duration: 0,
      lessons: 0,
      created_at: "2026-05-31T07:32:04.258Z",
    },
  ],
});
